"""Unofficial async client for SpaceXAI OAuth subscription APIs."""

from .client import SpaceXAISubscriptionClient
from .errors import (
    AuthenticationError,
    AuthorizationDeniedError,
    ConnectionFailureError,
    DeviceAuthorizationExpiredError,
    InvalidResponseError,
    RateLimitError,
    RequestTimeoutError,
    SpaceXAISubscriptionError,
)
from .models import (
    Account,
    Attachment,
    BuiltinTool,
    Completion,
    DeviceAuthorization,
    GeneratedImage,
    GeneratedVideo,
    InputItem,
    Message,
    OAuthToken,
    ResponseFormat,
    ResponseTool,
    Tool,
    ToolCall,
    ToolResult,
)

__all__ = [
    "Account",
    "Attachment",
    "AuthenticationError",
    "AuthorizationDeniedError",
    "BuiltinTool",
    "Completion",
    "ConnectionFailureError",
    "DeviceAuthorization",
    "DeviceAuthorizationExpiredError",
    "GeneratedImage",
    "GeneratedVideo",
    "InputItem",
    "InvalidResponseError",
    "Message",
    "OAuthToken",
    "RateLimitError",
    "RequestTimeoutError",
    "ResponseFormat",
    "ResponseTool",
    "SpaceXAISubscriptionClient",
    "SpaceXAISubscriptionError",
    "Tool",
    "ToolCall",
    "ToolResult",
]
